apiVersion: v1
kind: Service
metadata: 
  name: nestjs-svc
  labels: 
    app: nestjs-svc
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports: 
  - port: 80
    protocol: TCP
    targetPort: 3000
    